logging:
  level:
    org.springframework: trace
  structured:
    format:
      console: ecs
spring:
  application:
    name: Authorization Server
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          api-gateway:
            registration:
              client-id: "api-gateway"
              client-secret: "{noop}test"
              client-authentication-methods:
                - "none"
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://api-gateway/login/oauth2/code/api-gateway"
              post-logout-redirect-uris:
                - "http://api-gateway"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false
